version: '3'
services:
  scrapper:
    build: 
      context: scrapper
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment: 
      - FLASK_APP=flaskr
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
        - './scrapper:/app'

#  redis:
#    image: "redis:alpine"
