version: "3.3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - FLASK_APP=flaskr
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
        - '.:/app'
  redis:
    image: "redis:alpine"
